### PR TITLE
Alex november refactor

### PR DESCRIPTION
**Pull request by asooge**
Major refactoring of major components: Workspace, GoogleMap, Header, WorkspaceFilter. Attempt to fix console warnings that appear often. 

New functionality:
- navigate to workspace by route `/workspace/:id` allowing user to share links. Also simplifies logic to send user to a new workspace, for example from list view and header. Workspace handles the logic of fetching data on it's own. 
- refer user to sign in and redirect back to create a review or back to the workspace view on success. 
- google map uses `panTo` for smoother transitions between clicks. Also offsets the horizontal center when viewing workspace on desktop.

New visuals:
- updated map styles

Deployed build for testing: https://deploy-preview-278--stoic-bose-478137.netlify.app/#/

image

### CODE REVIEW

**Review by GMorse19 — COMMENTED** [review]
Everything looks great. I pulled the branch and played around with it some. Everything looks good, but I did run into an issue when trying to look at the workspaces.
Screen Shot 2020-11-28 at 9 00 42 PM

I reset the database and still get the same message. Is this something you ran into at all?

**Comment by asooge** [comment]
@GMorse19 I was using the deployed api url 'https://warm-chamber-62945.herokuapp.com/' for development. Try switching to the deployed apiUrl or master branch if you're running the api locally.

**Comment by GMorse19** [comment]
Indeed!! I was just in the process of doing that as I looked up the error message. Looks awesome!

**Comment by yingsongsana** [comment]
@asooge this is awesome work! I love that each workspace now has its own route for easy sharing. Great thinking! And the filter buttons look real clean in their own separate file 👌🏼

**Comment by asooge** [comment]
Thanks @yingsongsana I tried to make it easier to update and add new features. Still have a ways to go with the google map but this should hopefully be a good improvement.

**Pull request merged**
