### PR TITLE
Geoff add username

### PR DESCRIPTION
**Pull request by GMorse19**
Updated Signin.js and Signup.js to accommodate new columns in the API.

Switched `user.email` to `user.username` in Header.js

Added two form fields to SignUp for username and avatar.  This will need to be arranged somehow for users to choose an avatar.

### CODE REVIEW

**Comment by asooge** [comment]
@GMorse19 can you post screenshots of your updated sign-in and sign-up

**Comment by GMorse19** [comment]
Sign has remained the same. 

Screen Shot 2020-04-12 at 4 40 52 PM

**Comment by asooge** [comment]
I'm glad the functionality is working, but we should have a conversation about the UI before moving forward. My thoughts are 'Username' should be the first input. Avatar should be some kind of <select> dropdown. Also, going forward does username replace email, for example will the API reject the sign-up if username is already taken.

**Comment by GMorse19** [comment]
The signup fields are completely unnecessary for this pull request. I can remove them if desired.

**Comment by GMorse19** [comment]
I'm going to close this for now. No rush to get it to development just yet.

**Pull request closed without merging**
